"""Probabilistic skip list implementation.

A layered linked-list data structure providing O(log n) expected time
for search, insert, and delete operations using randomized leveling.
"""
from __future__ import annotations

import random
from typing import Any, Iterator


class _Node:
    """Internal skip list node holding a key, value, and forward pointers."""

    __slots__ = ("key", "value", "forward")

    def __init__(self, key: int, value: Any, level: int) -> None:
        self.key = key
        self.value = value
        # forward[i] = next node at level i (0-indexed)
        self.forward: list[_Node | None] = [None] * level


class SkipList:
    """Probabilistic skip list mapping integer keys to arbitrary values.

    Parameters
    ----------
    max_level : int
        Maximum number of layers. Caps the height generated by random promotion.
    p : float
        Promotion probability per layer (geometric distribution parameter).
    """

    def __init__(self, max_level: int = 16, p: float = 0.5) -> None:
        if max_level < 1:
            raise ValueError("max_level must be >= 1")
        if not (0.0 < p < 1.0):
            raise ValueError("p must be in (0, 1)")
        self._max_level = max_level
        self._p = p
        # Sentinel head node, full height; key/value are unused on the head.
        self._head: _Node = _Node(key=0, value=None, level=max_level)
        self._level = 1  # current highest in-use level (1-indexed count)
        self._size = 0
        self._rng = random.Random()

    # ---- Internal helpers ----

    def _random_level(self) -> int:
        """Return a random level in [1, max_level] using geometric distribution."""
        lvl = 1
        while lvl < self._max_level and self._rng.random() < self._p:
            lvl += 1
        return lvl

    # ---- Public API ----

    def insert(self, key: int, value: Any) -> None:
        """Insert key-value pair. If key exists, update its value in place."""
        update: list[_Node] = [self._head] * self._max_level
        cur = self._head
        for i in range(self._level - 1, -1, -1):
            nxt = cur.forward[i]
            while nxt is not None and nxt.key < key:
                cur = nxt
                nxt = cur.forward[i]
            update[i] = cur

        candidate = cur.forward[0]
        if candidate is not None and candidate.key == key:
            candidate.value = value
            return

        new_level = self._random_level()
        if new_level > self._level:
            for i in range(self._level, new_level):
                update[i] = self._head
            self._level = new_level

        new_node = _Node(key, value, new_level)
        for i in range(new_level):
            new_node.forward[i] = update[i].forward[i]
            update[i].forward[i] = new_node
        self._size += 1

    def delete(self, key: int) -> bool:
        """Remove key from all levels. Return True if removed, False if absent."""
        update: list[_Node] = [self._head] * self._max_level
        cur = self._head
        for i in range(self._level - 1, -1, -1):
            nxt = cur.forward[i]
            while nxt is not None and nxt.key < key:
                cur = nxt
                nxt = cur.forward[i]
            update[i] = cur

        target = cur.forward[0]
        if target is None or target.key != key:
            return False

        for i in range(self._level):
            if update[i].forward[i] is not target:
                break
            update[i].forward[i] = target.forward[i]

        # shrink current level if topmost layers are now empty
        while self._level > 1 and self._head.forward[self._level - 1] is None:
            self._level -= 1

        self._size -= 1
        return True

    def search(self, key: int) -> Any | None:
        """Return value for key, or None if absent."""
        cur = self._head
        for i in range(self._level - 1, -1, -1):
            nxt = cur.forward[i]
            while nxt is not None and nxt.key < key:
                cur = nxt
                nxt = cur.forward[i]
        candidate = cur.forward[0]
        if candidate is not None and candidate.key == key:
            return candidate.value
        return None

    def range_query(self, lo: int, hi: int) -> list[tuple[int, Any]]:
        """Return sorted list of (key, value) where lo <= key <= hi."""
        if lo > hi:
            return []
        # find first node with key >= lo via top-down traversal
        cur = self._head
        for i in range(self._level - 1, -1, -1):
            nxt = cur.forward[i]
            while nxt is not None and nxt.key < lo:
                cur = nxt
                nxt = cur.forward[i]
        node = cur.forward[0]
        result: list[tuple[int, Any]] = []
        while node is not None and node.key <= hi:
            result.append((node.key, node.value))
            node = node.forward[0]
        return result

    def __len__(self) -> int:
        return self._size

    def __contains__(self, key: object) -> bool:
        if not isinstance(key, int) or isinstance(key, bool):
            # treat non-int as not present; reject bool to avoid surprises
            if not isinstance(key, int):
                return False
        cur = self._head
        for i in range(self._level - 1, -1, -1):
            nxt = cur.forward[i]
            while nxt is not None and nxt.key < key:
                cur = nxt
                nxt = cur.forward[i]
        candidate = cur.forward[0]
        return candidate is not None and candidate.key == key

    def __iter__(self) -> Iterator[tuple[int, Any]]:
        node = self._head.forward[0]
        while node is not None:
            yield (node.key, node.value)
            node = node.forward[0]

    def __repr__(self) -> str:
        return f"SkipList(size={self._size}, level={self._level}, max_level={self._max_level}, p={self._p})"
